# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 433)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(20, 10, 20, 40)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.open_reply = QtWidgets.QPushButton(self.centralwidget)
        self.open_reply.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.open_reply.setFont(font)
        self.open_reply.setStyleSheet("background-color:rgb(149,236,105);")
        self.open_reply.setObjectName("open_reply")
        self.verticalLayout.addWidget(self.open_reply)
        self.close_reply = QtWidgets.QPushButton(self.centralwidget)
        self.close_reply.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.close_reply.setFont(font)
        self.close_reply.setStyleSheet("background-color:rgb(149,236,105);")
        self.close_reply.setObjectName("close_reply")
        self.verticalLayout.addWidget(self.close_reply)
        self.timer_set = QtWidgets.QPushButton(self.centralwidget)
        self.timer_set.setMinimumSize(QtCore.QSize(139, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.timer_set.setFont(font)
        self.timer_set.setStyleSheet("background-color:rgb(149,236,105);")
        self.timer_set.setObjectName("timer_set")
        self.verticalLayout.addWidget(self.timer_set)
        self.introduction = QtWidgets.QPushButton(self.centralwidget)
        self.introduction.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.introduction.setFont(font)
        self.introduction.setStyleSheet("background-color:rgb(149,236,105);")
        self.introduction.setObjectName("introduction")
        self.verticalLayout.addWidget(self.introduction)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.infomation_area = QtWidgets.QTextBrowser(self.centralwidget)
        self.infomation_area.setStyleSheet("background-color:rgb(149,236,105);")
        self.infomation_area.setObjectName("infomation_area")
        self.horizontalLayout.addWidget(self.infomation_area)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "自动聊天机器人"))
        self.open_reply.setText(_translate("MainWindow", "开启自动回复"))
        self.close_reply.setText(_translate("MainWindow", "关闭自动回复"))
        self.timer_set.setText(_translate("MainWindow", "定时设定"))
        self.introduction.setText(_translate("MainWindow", "使用说明"))

