# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 433)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(20, 10, 20, 40)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.auto_reply = QtWidgets.QPushButton(self.centralwidget)
        self.auto_reply.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.auto_reply.setFont(font)
        self.auto_reply.setStyleSheet("background-color:rgb(149,236,105);")
        self.auto_reply.setObjectName("auto_reply")
        self.verticalLayout.addWidget(self.auto_reply)
        self.film_filter = QtWidgets.QPushButton(self.centralwidget)
        self.film_filter.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.film_filter.setFont(font)
        self.film_filter.setStyleSheet("background-color:rgb(149,236,105);")
        self.film_filter.setObjectName("film_filter")
        self.verticalLayout.addWidget(self.film_filter)
        self.message_back = QtWidgets.QPushButton(self.centralwidget)
        self.message_back.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.message_back.setFont(font)
        self.message_back.setStyleSheet("background-color:rgb(149,236,105);")
        self.message_back.setObjectName("message_back")
        self.verticalLayout.addWidget(self.message_back)
        self.timer_set = QtWidgets.QPushButton(self.centralwidget)
        self.timer_set.setMinimumSize(QtCore.QSize(139, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.timer_set.setFont(font)
        self.timer_set.setStyleSheet("background-color:rgb(149,236,105);")
        self.timer_set.setObjectName("timer_set")
        self.verticalLayout.addWidget(self.timer_set)
        self.introduction = QtWidgets.QPushButton(self.centralwidget)
        self.introduction.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.introduction.setFont(font)
        self.introduction.setStyleSheet("background-color:rgb(149,236,105);")
        self.introduction.setObjectName("introduction")
        self.verticalLayout.addWidget(self.introduction)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(3, 2)
        self.verticalLayout.setStretch(4, 2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.infomation_area = QtWidgets.QTextBrowser(self.centralwidget)
        self.infomation_area.setStyleSheet("background-color:rgb(149,236,105);")
        self.infomation_area.setObjectName("infomation_area")
        self.horizontalLayout.addWidget(self.infomation_area)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionsetting = QtWidgets.QAction(MainWindow)
        self.actionsetting.setObjectName("actionsetting")
        self.menu.addAction(self.actionsetting)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "自动微信机器人"))
        self.auto_reply.setText(_translate("MainWindow", "开启自动回复"))
        self.film_filter.setText(_translate("MainWindow", "防剧透助手"))
        self.message_back.setText(_translate("MainWindow", "防撤回工具"))
        self.timer_set.setText(_translate("MainWindow", "定时设定"))
        self.introduction.setText(_translate("MainWindow", "使用说明"))
        self.menu.setTitle(_translate("MainWindow", "设置"))
        self.actionsetting.setText(_translate("MainWindow", "系统设置"))

