# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(816, 630)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(0.9)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.leftWidget = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        self.leftWidget.setFont(font)
        self.leftWidget.setStyleSheet("QWidget#leftWidget{\n"
"background:gray;\n"
"border-top:1px solid white;\n"
"border-bottom:1px solid white;\n"
"border-left:1px solid white;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"}\n"
"QLabel{border:none;color:white;}\n"
"QGroupBox{color:white;}\n"
"QRadioButton{color:white;}\n"
"QPushButton{\n"
"border:none;\n"
"color:white;\n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"font-size:18px;\n"
"font-weight:700;}")
        self.leftWidget.setObjectName("leftWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftWidget)
        self.verticalLayout_3.setContentsMargins(5, 45, 5, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.leftWidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.wakeUpEdit = QtWidgets.QTimeEdit(self.groupBox_2)
        self.wakeUpEdit.setObjectName("wakeUpEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.wakeUpEdit)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lunchTimeEdit = QtWidgets.QTimeEdit(self.groupBox_2)
        self.lunchTimeEdit.setObjectName("lunchTimeEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lunchTimeEdit)
        self.dinnerTimeEdit = QtWidgets.QTimeEdit(self.groupBox_2)
        self.dinnerTimeEdit.setObjectName("dinnerTimeEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dinnerTimeEdit)
        self.sleepTimeEdit = QtWidgets.QTimeEdit(self.groupBox_2)
        self.sleepTimeEdit.setObjectName("sleepTimeEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sleepTimeEdit)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.leftWidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.talkOnButton = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.talkOnButton.setFont(font)
        self.talkOnButton.setObjectName("talkOnButton")
        self.horizontalLayout_4.addWidget(self.talkOnButton)
        self.talkOffButton = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.talkOffButton.setFont(font)
        self.talkOffButton.setObjectName("talkOffButton")
        self.horizontalLayout_4.addWidget(self.talkOffButton)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.appIDEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.appIDEdit.setObjectName("appIDEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.appIDEdit)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.appKeyEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.appKeyEdit.setObjectName("appKeyEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.appKeyEdit)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.weathOnButton = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.weathOnButton.setFont(font)
        self.weathOnButton.setObjectName("weathOnButton")
        self.horizontalLayout_5.addWidget(self.weathOnButton)
        self.weathOffButton = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.weathOffButton.setFont(font)
        self.weathOffButton.setObjectName("weathOffButton")
        self.horizontalLayout_5.addWidget(self.weathOffButton)
        self.formLayout_3.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.emojiOnButton = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.emojiOnButton.setFont(font)
        self.emojiOnButton.setObjectName("emojiOnButton")
        self.horizontalLayout_6.addWidget(self.emojiOnButton)
        self.emojiOffButton = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.emojiOffButton.setFont(font)
        self.emojiOffButton.setObjectName("emojiOffButton")
        self.horizontalLayout_6.addWidget(self.emojiOffButton)
        self.formLayout_3.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.gridLayout.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.leftWidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.wechatNameEdit = QtWidgets.QLineEdit(self.groupBox)
        self.wechatNameEdit.setObjectName("wechatNameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.wechatNameEdit)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.nickNameEdit = QtWidgets.QLineEdit(self.groupBox)
        self.nickNameEdit.setObjectName("nickNameEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nickNameEdit)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.birthMonthBox = QtWidgets.QSpinBox(self.groupBox)
        self.birthMonthBox.setMinimum(1)
        self.birthMonthBox.setMaximum(12)
        self.birthMonthBox.setObjectName("birthMonthBox")
        self.horizontalLayout.addWidget(self.birthMonthBox)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.birthDayBox = QtWidgets.QSpinBox(self.groupBox)
        self.birthDayBox.setMinimum(1)
        self.birthDayBox.setMaximum(31)
        self.birthDayBox.setObjectName("birthDayBox")
        self.horizontalLayout.addWidget(self.birthDayBox)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(2, 2)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.memDateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.memDateEdit.setObjectName("memDateEdit")
        self.horizontalLayout_2.addWidget(self.memDateEdit)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.startUpButton = QtWidgets.QPushButton(self.leftWidget)
        self.startUpButton.setObjectName("startUpButton")
        self.gridLayout.addWidget(self.startUpButton, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.groupBox_3 = QtWidgets.QGroupBox(self.leftWidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.valentineDayEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.valentineDayEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.valentineDayEdit.setObjectName("valentineDayEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.valentineDayEdit)
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.womenDayEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.womenDayEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.womenDayEdit.setObjectName("womenDayEdit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.womenDayEdit)
        self.christmasEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.christmasEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.christmasEdit.setObjectName("christmasEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.christmasEdit)
        self.birthDayEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.birthDayEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.birthDayEdit.setObjectName("birthDayEdit")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.birthDayEdit)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout_7.addWidget(self.leftWidget)
        self.rightWidget = QtWidgets.QWidget(self.centralwidget)
        self.rightWidget.setStyleSheet("QWidget#rightWidget{\n"
"color:#232C51;\n"
"background:white;\n"
"border-top:1px solid darkGray;\n"
"border-bottom:1px solid darkGray;\n"
"border-right:1px solid darkGray;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}")
        self.rightWidget.setObjectName("rightWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rightWidget)
        self.verticalLayout_2.setContentsMargins(10, 5, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.rightWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton.setStyleSheet("QPushButton{background:#F7D674;border-radius:10px;}QPushButton:hover{background:yellow;}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.rightWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_3.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_3.setStyleSheet("QPushButton{background:#F76677;border-radius:10px;}QPushButton:hover{background:red;}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_22 = QtWidgets.QLabel(self.rightWidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_2.addWidget(self.label_22)
        self.MsgBrowser = QtWidgets.QTextBrowser(self.rightWidget)
        self.MsgBrowser.setObjectName("MsgBrowser")
        self.verticalLayout_2.addWidget(self.MsgBrowser)
        self.horizontalLayout_7.addWidget(self.rightWidget)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_3.clicked.connect(MainWindow.close)
        self.pushButton.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "她的作息"))
        self.label_6.setText(_translate("MainWindow", "起床时间"))
        self.label_7.setText(_translate("MainWindow", "午饭时间"))
        self.label_8.setText(_translate("MainWindow", "晚餐时间"))
        self.label_9.setText(_translate("MainWindow", "睡觉时间"))
        self.groupBox_4.setTitle(_translate("MainWindow", "系统配置"))
        self.label_13.setText(_translate("MainWindow", "自动聊天"))
        self.talkOnButton.setText(_translate("MainWindow", "开"))
        self.talkOffButton.setText(_translate("MainWindow", "关"))
        self.label_14.setText(_translate("MainWindow", "应用ID"))
        self.label_15.setText(_translate("MainWindow", "应用KEY"))
        self.label_16.setText(_translate("MainWindow", "气象提醒"))
        self.weathOnButton.setText(_translate("MainWindow", "开"))
        self.weathOffButton.setText(_translate("MainWindow", "关"))
        self.label_17.setText(_translate("MainWindow", "结尾表情"))
        self.emojiOnButton.setText(_translate("MainWindow", "开"))
        self.emojiOffButton.setText(_translate("MainWindow", "关"))
        self.groupBox.setTitle(_translate("MainWindow", "女孩信息"))
        self.label.setText(_translate("MainWindow", "妹子微信名"))
        self.label_2.setText(_translate("MainWindow", "妹子昵称"))
        self.label_3.setText(_translate("MainWindow", "妹子生日"))
        self.label_4.setText(_translate("MainWindow", "月"))
        self.label_5.setText(_translate("MainWindow", "日"))
        self.label_10.setText(_translate("MainWindow", "你们的日子"))
        self.memDateEdit.setDisplayFormat(_translate("MainWindow", "yyyy年MM月dd日"))
        self.startUpButton.setText(_translate("MainWindow", "启动"))
        self.groupBox_3.setTitle(_translate("MainWindow", "节日语录"))
        self.label_18.setText(_translate("MainWindow", "情人节"))
        self.label_19.setText(_translate("MainWindow", "妇女节"))
        self.label_20.setText(_translate("MainWindow", "平安夜"))
        self.label_21.setText(_translate("MainWindow", "生日"))
        self.pushButton.setText(_translate("MainWindow", "-"))
        self.pushButton_3.setText(_translate("MainWindow", "X"))
        self.label_22.setText(_translate("MainWindow", "记录文本"))

