# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analysis.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg


class Ui_nmonAnalysis_Form(object):
    def setupUi(self, nmonAnalysis_Form):
        nmonAnalysis_Form.setObjectName("nmonAnalysis_Form")
        nmonAnalysis_Form.resize(970, 516)
        self.verticalLayout = QtWidgets.QVBoxLayout(nmonAnalysis_Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(nmonAnalysis_Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ip_lineEdit = QtWidgets.QLineEdit(nmonAnalysis_Form)
        self.ip_lineEdit.setReadOnly(True)
        self.ip_lineEdit.setObjectName("ip_lineEdit")
        self.horizontalLayout.addWidget(self.ip_lineEdit)
        self.label_2 = QtWidgets.QLabel(nmonAnalysis_Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.fileName_lineEdit = QtWidgets.QLineEdit(nmonAnalysis_Form)
        self.fileName_lineEdit.setReadOnly(True)
        self.fileName_lineEdit.setObjectName("fileName_lineEdit")
        self.horizontalLayout.addWidget(self.fileName_lineEdit)
        self.label_3 = QtWidgets.QLabel(nmonAnalysis_Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.simpleNum_label = QtWidgets.QLabel(nmonAnalysis_Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.simpleNum_label.setFont(font)
        self.simpleNum_label.setText("")
        self.simpleNum_label.setObjectName("simpleNum_label")
        self.horizontalLayout.addWidget(self.simpleNum_label)
        self.analysis_pushButton = QtWidgets.QPushButton(nmonAnalysis_Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.analysis_pushButton.setFont(font)
        self.analysis_pushButton.setObjectName("analysis_pushButton")
        self.horizontalLayout.addWidget(self.analysis_pushButton)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 3)
        self.horizontalLayout.setStretch(5, 3)
        self.horizontalLayout.setStretch(6, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(nmonAnalysis_Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 5, 0, 1, 1)
        self.star_spinBox = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.star_spinBox.setFont(font)
        self.star_spinBox.setObjectName("star_spinBox")
        self.gridLayout_3.addWidget(self.star_spinBox, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.cpu_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.cpu_label.setFont(font)
        self.cpu_label.setText("")
        self.cpu_label.setObjectName("cpu_label")
        self.gridLayout_3.addWidget(self.cpu_label, 2, 1, 1, 1)
        self.men_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.men_label.setFont(font)
        self.men_label.setText("")
        self.men_label.setObjectName("men_label")
        self.gridLayout_3.addWidget(self.men_label, 3, 1, 1, 1)
        self.end_spinBox = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.end_spinBox.setFont(font)
        self.end_spinBox.setObjectName("end_spinBox")
        self.gridLayout_3.addWidget(self.end_spinBox, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 1, 2, 1, 1)
        self.net_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.net_label.setFont(font)
        self.net_label.setText("")
        self.net_label.setObjectName("net_label")
        self.gridLayout_3.addWidget(self.net_label, 4, 1, 1, 1)
        self.IOPS_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.IOPS_label.setFont(font)
        self.IOPS_label.setText("")
        self.IOPS_label.setObjectName("IOPS_label")
        self.gridLayout_3.addWidget(self.IOPS_label, 6, 1, 1, 1)
        self.disk_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.disk_label.setFont(font)
        self.disk_label.setText("")
        self.disk_label.setObjectName("disk_label")
        self.gridLayout_3.addWidget(self.disk_label, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 2)
        self.gridLayout_3.setColumnStretch(1, 2)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(nmonAnalysis_Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cpu_widget = pg.PlotWidget(self.tab)
        self.cpu_widget.setMinimumSize(QtCore.QSize(300, 200))
        self.cpu_widget.setObjectName("graph_widget")
        self.cpu_widget.showGrid(x=True, y=True, alpha=0.5)  # 显示图形网格
        self.cpu_widget.setLabel(axis='left', text='百分比(%)')  # 设置Y轴标签
        self.cpu_widget.setYRange(0, 150) # 初始化Y轴显示范围
        self.cpu_widget.setXRange(0, 25, padding=0) # 初始化X轴显示范围
        self.cpu_widget.setLabel(axis='bottom', text='采样点(个)')  # 设置X轴标签
        self.cpu_widget.addLegend(size=(20, 10), offset=(12, 12)) # 添加图示x
        self.cpu_point_label = pg.TextItem()  # 创建一个文本项
        self.cpu_widget.addItem(self.cpu_point_label)  # 在图形部件中添加文本项
        self.cpu_user_line = self.cpu_widget.plot(pen="g", name="CPU用户使用率", symbolBrush="g")
        self.cpu_sys_line = self.cpu_widget.plot(pen=(255,180,0), name="CPU系统使用率", symbolBrush=(255,180,0))
        self.cpu_idle_line = self.cpu_widget.plot(pen=(0,249,255), name="CPU空闲率", symbolBrush=(0,249,255))
        self.cpu_vLine = pg.InfiniteLine(angle=90, movable=False, pen="w")
        self.cpu_widget.addItem(self.cpu_vLine, ignoreBounds=True)
        self.verticalLayout_4.addWidget(self.cpu_widget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mem_widget = pg.PlotWidget(self.tab_2)
        self.mem_widget.setMinimumSize(QtCore.QSize(300, 200))
        self.mem_widget.setObjectName("graph_widget")
        self.mem_widget.showGrid(x=True, y=True, alpha=0.5)  # 显示图形网格
        self.mem_widget.setLabel(axis='left', text='百分比(%)')  # 设置Y轴标签
        self.mem_widget.setYRange(0, 150) # 初始化Y轴显示范围
        self.mem_widget.setXRange(0, 25, padding=0) # 初始化X轴显示范围
        self.mem_widget.setLabel(axis='bottom', text='采样点(个)')  # 设置X轴标签
        self.mem_widget.addLegend(size=(20, 10), offset=(12, 12)) # 添加图示x
        self.mem_point_label = pg.TextItem()  # 创建一个文本项
        self.mem_widget.addItem(self.mem_point_label)  # 在图形部件中添加文本项
        self.mem_line = self.mem_widget.plot(pen="g", name="内存使用率", symbolBrush="g")
        self.mem_vLine = pg.InfiniteLine(angle=90, movable=False, pen="w")
        self.mem_widget.addItem(self.mem_vLine, ignoreBounds=True)
        self.verticalLayout_5.addWidget(self.mem_widget)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.disk_widget = pg.PlotWidget(self.tab_3)
        self.disk_widget.setMinimumSize(QtCore.QSize(300, 200))
        self.disk_widget.setObjectName("graph_widget")
        self.disk_widget.showGrid(x=True, y=True, alpha=0.5)  # 显示图形网格
        self.disk_widget.setLabel(axis='left', text='使用率(%)')  # 设置Y轴标签
        self.disk_widget.setYRange(0, 200) # 初始化Y轴显示范围
        self.disk_widget.setXRange(0, 25, padding=0) # 初始化X轴显示范围
        self.disk_widget.setLabel(axis='bottom', text='采样点(个)')  # 设置X轴标签
        self.disk_widget.addLegend(size=(20, 10), offset=(12, 12)) # 添加图示
        self.disk_point_label = pg.TextItem()  # 创建一个文本项
        self.disk_widget.addItem(self.disk_point_label)  # 在图形部件中添加文本项
        self.disk_vLine = pg.InfiniteLine(angle=90, movable=False, pen="w")
        self.disk_widget.addItem(self.disk_vLine, ignoreBounds=True)
        self.verticalLayout_6.addWidget(self.disk_widget)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.iops_widget = pg.PlotWidget(self.tab_4)
        self.iops_widget.setMinimumSize(QtCore.QSize(300, 200))
        self.iops_widget.setObjectName("graph_widget")
        self.iops_widget.showGrid(x=True, y=True, alpha=0.5)  # 显示图形网格
        self.iops_widget.setLabel(axis='left', text='IO/sec')  # 设置Y轴标签
        self.iops_widget.setYRange(0, 600) # 初始化Y轴显示范围
        self.iops_widget.setXRange(0, 25, padding=0) # 初始化X轴显示范围
        self.iops_widget.setLabel(axis='bottom', text='采样点(个)')  # 设置X轴标签
        self.iops_widget.addLegend(size=(20, 10), offset=(12, 12)) # 添加图示x
        self.iops_point_label = pg.TextItem()  # 创建一个文本项
        self.iops_widget.addItem(self.iops_point_label)  # 在图形部件中添加文本项
        self.iops_line = self.iops_widget.plot(pen=(228,164,255), name="磁盘IO/sec", symbolBrush=(228,164,255))
        self.iops_vLine = pg.InfiniteLine(angle=90, movable=False, pen="w")
        self.iops_widget.addItem(self.iops_vLine, ignoreBounds=True)
        self.verticalLayout_7.addWidget(self.iops_widget)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.net_widget = pg.PlotWidget(self.tab_5)
        self.net_widget.setMinimumSize(QtCore.QSize(300, 200))
        self.net_widget.setObjectName("graph_widget")
        self.net_widget.showGrid(x=True, y=True, alpha=0.5)  # 显示图形网格
        self.net_widget.setLabel(axis='left', text='Mbps')  # 设置Y轴标签
        self.net_widget.setYRange(0, 200) # 初始化Y轴显示范围
        self.net_widget.setXRange(0, 25, padding=0) # 初始化X轴显示范围
        self.net_widget.setLabel(axis='bottom', text='采样点(个)')  # 设置X轴标签
        self.net_widget.addLegend(size=(20, 10), offset=(12, 12)) # 添加图示
        self.net_point_label = pg.TextItem()  # 创建一个文本项
        self.net_widget.addItem(self.net_point_label)  # 在图形部件中添加文本项
        self.net_read_line = self.net_widget.plot(pen="r", name="网络-读", symbolBrush=(255,0,0))
        self.net_write_line = self.net_widget.plot(pen="g", name="网络-写", symbolBrush=(0, 255, 0))
        self.net_vLine = pg.InfiniteLine(angle=90, movable=False, pen="w")
        self.net_widget.addItem(self.net_vLine, ignoreBounds=True)
        self.verticalLayout_8.addWidget(self.net_widget)
        self.tabWidget.addTab(self.tab_5, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(nmonAnalysis_Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(nmonAnalysis_Form)

    def retranslateUi(self, nmonAnalysis_Form):
        _translate = QtCore.QCoreApplication.translate
        nmonAnalysis_Form.setWindowTitle(_translate("nmonAnalysis_Form", "nmon数据分析"))
        self.label.setText(_translate("nmonAnalysis_Form", "数据来源ip:"))
        self.label_2.setText(_translate("nmonAnalysis_Form", "数据来源文件："))
        self.label_3.setText(_translate("nmonAnalysis_Form", "采样数："))
        self.analysis_pushButton.setText(_translate("nmonAnalysis_Form", "分析"))
        self.groupBox.setTitle(_translate("nmonAnalysis_Form", "nmon信息"))
        self.label_5.setText(_translate("nmonAnalysis_Form", "开始采样点："))
        self.label_6.setText(_translate("nmonAnalysis_Form", "结束采样点"))
        self.label_11.setText(_translate("nmonAnalysis_Form", "网络吞吐量(mbps):"))
        self.label_13.setText(_translate("nmonAnalysis_Form", "IO使用率(%):"))
        self.label_16.setText(_translate("nmonAnalysis_Form", "IOPS(次):"))
        self.label_9.setText(_translate("nmonAnalysis_Form", "内存使用率(%):"))
        self.pushButton_2.setText(_translate("nmonAnalysis_Form", "数据刷新"))
        self.pushButton_4.setText(_translate("nmonAnalysis_Form", "导出"))
        self.label_7.setText(_translate("nmonAnalysis_Form", "CPU使用率(%):"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("nmonAnalysis_Form", "CPU"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("nmonAnalysis_Form", "内存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("nmonAnalysis_Form", "磁盘"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("nmonAnalysis_Form", "IOPS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("nmonAnalysis_Form", "网络"))

