# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timer_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_timer_Dialog(object):
    def setupUi(self, timer_Dialog):
        timer_Dialog.setObjectName("timer_Dialog")
        timer_Dialog.resize(349, 116)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(timer_Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(timer_Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(timer_Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(timer_Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tap_spinBox = QtWidgets.QSpinBox(timer_Dialog)
        self.tap_spinBox.setObjectName("tap_spinBox")
        self.tap_spinBox.setMinimum(0)
        self.tap_spinBox.setMaximum(6000)
        self.horizontalLayout.addWidget(self.tap_spinBox)
        self.label_6 = QtWidgets.QLabel(timer_Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.horizontalLayout.setStretch(0, 9)
        self.horizontalLayout.setStretch(1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.time_spinBox = QtWidgets.QSpinBox(timer_Dialog)
        self.time_spinBox.setObjectName("time_spinBox")
        self.time_spinBox.setMinimum(0)
        self.time_spinBox.setMaximum(60)
        self.horizontalLayout_3.addWidget(self.time_spinBox)
        self.label_5 = QtWidgets.QLabel(timer_Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_3.setStretch(0, 9)
        self.horizontalLayout_3.setStretch(1, 1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fileName_lineEdit = QtWidgets.QLineEdit(timer_Dialog)
        self.fileName_lineEdit.setObjectName("fileName_lineEdit")
        self.horizontalLayout_4.addWidget(self.fileName_lineEdit)
        self.label_4 = QtWidgets.QLabel(timer_Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(timer_Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).setText('确定')
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel).setText('取消')
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.horizontalLayout_2.setStretch(1, 3)

        self.retranslateUi(timer_Dialog)
        self.buttonBox.accepted.connect(timer_Dialog.accept)
        self.buttonBox.rejected.connect(timer_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(timer_Dialog)

    def retranslateUi(self, timer_Dialog):
        _translate = QtCore.QCoreApplication.translate
        timer_Dialog.setWindowTitle(_translate("timer_Dialog", "nmon设置"))
        self.label.setText(_translate("timer_Dialog", "采样次数："))
        self.label_2.setText(_translate("timer_Dialog", "间隔时间："))
        self.label_3.setText(_translate("timer_Dialog", "文件名称："))
        self.label_6.setText(_translate("timer_Dialog", "次"))
        self.label_5.setText(_translate("timer_Dialog", "秒"))
        self.label_4.setText(_translate("timer_Dialog", ".nmon"))

